Apply backticks to `OPT_LEVEL`
To fix this lint that turned up when I upgraded to rust 1.89

```
error: item in documentation is missing backticks
  --> /tmp/target_docker/debug/build/.../out/built.rs:79:19
   |
79 | #[doc=r#"Value of OPT_LEVEL for the profile used during compilation."#]
```

The lint in question being: https://rust-lang.github.io/rust-clippy/master/index.html#doc_markdown.